apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongodb-pv
spec:
  capacity:
    storage: 1Gi  
  accessModes:
    - ReadWriteOnce 
  storageClassName: standard 
  hostPath:
    path: /data/mongodb  
