apiVersion: v1
kind: Service
metadata:
  name: episode4-frontend
spec:
  selector:
    app: episode4-frontend
  ports:
    - protocol: TCP
      port: 83
      targetPort: 83
  type: NodePort
