apiVersion: apps/v1
kind: Deployment
metadata:
  name: episode4-backend
  labels:
    app: episode4-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: episode4-backend
  template:
    metadata:
      labels:
        app: episode4-backend
    spec:
      containers:
      - name: backend
        image: aghaali1/episode4-backend-image:latest  
        ports:
        - containerPort: 3003
        volumeMounts:
        - name: mongodb-data
          mountPath: /data/db
        env:
        - name: MONGO_DB_SECRET
          valueFrom:
            secretKeyRef:
              name: mongodb-secret-episode4  
              key: MONGO_DB_SECRET
      volumes:
      - name: mongodb-data
        persistentVolumeClaim:
          claimName: mongodb-pvc
