apiVersion: v1
kind: Service
metadata:
  name: episode3-frontend
spec:
  selector:
    app: episode3-frontend
  ports:
    - protocol: TCP
      port: 82
      targetPort: 82
  type: NodePort
