apiVersion: v1
kind: Service
metadata:
  name: episode5-frontend
spec:
  selector:
    app: episode5-frontend
  ports:
    - protocol: TCP
      port: 84
      targetPort: 84
  type: NodePort
