apiVersion: apps/v1
kind: Deployment
metadata:
  name: episode2-backend
  labels:
    app: episode2-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: episode2-backend
  template:
    metadata:
      labels:
        app: episode2-backend
    spec:
      containers:
      - name: backend
        image: aghaali1/episode2-backend-image:latest  
        ports:
        - containerPort: 3001
        volumeMounts:
        - name: mongodb-data
          mountPath: /data/db
        env:
        - name: MONGO_DB_SECRET
          valueFrom:
            secretKeyRef:
              name: mongodb-secret-episode2  
              key: MONGO_DB_SECRET
      volumes:
      - name: mongodb-data
        persistentVolumeClaim:
          claimName: mongodb-pvc
