apiVersion: v1
kind: Service
metadata:
  name: episode1-backend-service
  labels:
    app: episode1-backend
spec:
  selector:
    app: episode1-backend
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: ClusterIP
